name: "Native Build"

"on":
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        default: false
        description: "Release build"
      macos:
        type: boolean
        default: true
        description: "macOS"
      linux:
        type: boolean
        default: true
        description: "Linux"
      windows:
        type: boolean
        default: false
        description: "Windows"
      artifact:
        type: string
        default: ""
        description: "Artifact prefix"

  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
        description: "Release build"
      macos:
        type: boolean
        default: true
        description: "macOS"
      linux:
        type: boolean
        default: true
        description: "Linux"
      windows:
        type: boolean
        default: false
        description: "Windows"
      artifact:
        type: string
        default: ""
        description: "Artifact prefix"

    secrets:
      GRADLE_CONFIGURATION_KEY:
        description: "Gradle cache key"
        required: false
      BUILDLESS_APIKEY:
        description: "Buildless key"
        required: false

permissions:
  contents: read

jobs:
  ##
  ## Job: Build+Submit Dependency Graph
  ##
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu]
        mode: ["Strict"]
        tag: ["linux-amd64-${{ fromJson(inputs.release) && 'opt' || 'dev' }}"]
        machine: ["ubuntu-latest"]
        target: [":pkl-cli:linuxExecutableAmd64"]
        enabled:
          - ${{ fromJson(inputs.linux) }}
        include:
          - os: macOS x64
            tag: macos-x64-${{ fromJson(inputs.release) && 'opt' || 'dev' }}
            machine: macos-13
            target: :pkl-cli:macExecutableAmd64
            enabled: ${{ fromJson(inputs.macos) }}
          - os: macOS aarch64
            tag: macos-aarch64-${{ fromJson(inputs.release) && 'opt' || 'dev' }}
            machine: macos-13-xlarge
            target: :pkl-cli:macExecutableAarch64
            enabled: ${{ fromJson(inputs.macos) }}

          # Windows build is currently broken.
          #
          # - os: Windows
          #   machine: windows-latest
          #   target: :pkl-cli:windowsAmd64
          #   tag: windows-x64

    name: "Native CLI (${{ matrix.os }})"
    runs-on: ${{ matrix.machine }}

    defaults:
      run:
        shell: bash

    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        if: ${{ matrix.enabled }}
        with:
          submodules: true
          persist-credentials: false
      - name: "Setup: Cache Restore (Build)"
        id: cache-restore-build
        uses: actions/cache/restore@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        if: ${{ matrix.enabled }}
        with:
          key: pkl-v1-build-${{ hashFiles('gradle/libs.versions.toml') }}
          restore-keys: |
            pkl-v1-build-${{ hashFiles('gradle/libs.versions.toml') }}
            pkl-v1-build-
            pkl-v1-
            pkl-
          path: |
            .gradle/
            build/
            .codebase/
            .kotlin/
            ./*/build/bin
            ./*/build/classes
            ./*/build/kotlin
            ./*/build/klib
            ./*/build/generated
            ./*/build/generated-sources
      - name: "Setup: Java 21"
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        if: ${{ matrix.enabled }}
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: "Setup: GraalVM (Java 21)"
        uses: graalvm/setup-graalvm@d72e3dbf5f44eb0b78c4f8ec61a262d8bf9b94af # v1.1.7
        if: ${{ matrix.enabled }}
        with:
          distribution: "graalvm"
          java-version: 21
          check-for-updates: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: 'false'
          native-image-job-reports: 'true'
      - name: "🛠️ Build"
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        id: gradlebuild
        if: ${{ matrix.enabled }}
        env:
          CI: true
        with:
          build-scan-publish: true
          build-scan-terms-of-service-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-service-agree: "yes"
          cache-read-only: true
          cache-encryption-key: ${{ secrets.GRADLE_CONFIGURATION_KEY }}
          gradle-home-cache-cleanup: true
          arguments: |
            assemble
            build
            ${{ matrix.target || ':pkl-cli:assembleNative' }}
            -PnativeRelease=${{ inputs.release }}
            --scan
            -x test
            -x check
      - name: "Artifact: Native CLI"
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        if: ${{ matrix.enabled }}
        with:
          name: "${{ inputs.artifact || 'pkl-cli-latest' }}-${{ matrix.tag }}"
          path: ./pkl-cli/build/distributions/pkl*.*
          if-no-files-found: warn
          retention-days: 14
          compression-level: 1
          overwrite: true
      - name: "Artifact: Caches"
        uses: actions/cache/save@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        if: ${{ matrix.enabled }}
        with:
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
          path: |
            .gradle/
            build/
            .codebase/
            .kotlin/
            ./*/build/bin
            ./*/build/classes
            ./*/build/kotlin
            ./*/build/klib
            ./*/build/generated
            ./*/build/generated-sources
